variables:
  imageName: 'jannemattila/echo'

trigger:
- master
- develop

name: 1.0.$(Rev:r)
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(imageName):$(Build.BuildNumber)
          $(imageName):latest
