apiVersion: v1
kind: Namespace
metadata:
  name: echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: echo
spec:
  selector:
    app: echo
  ports:
  - port: 31111
    nodePort: 31111
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo  
  template:
    metadata:
      labels:
        app: echo
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - image: jannemattila/echo:latest
        name: echo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
