apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  selector:
    app: echo
  ports:
  - port: 31111
    nodePort: 31111
    targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: jannemattila/echo:latest
        name: echo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
